language: cpp
dist: bionic

addons:
  apt:
   packages:
   - libboost-test-dev
   - doxygen
   - graphviz

script:
        - set -e
        - cmake .
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target doc
        - cmake --build . --target package      
deploy:
  - provider: bintray
    file: bintray_test.json
    user: khatrox
    key: ${BINTRAY_API}
    skip_cleanup: true

  - provider: pages
    github_token: ${GITHUB_TOKEN}
    skip_cleanup: true
    keep_history: false
    local_dir: html
    on:
            branch: master
